
export interface Society {
  id: string;
  name: string;
  category: 'Technical' | 'Cultural' | 'Social' | 'Hobby';
  logo: string;
  aiHint: string;
  description: string;
}

export const allSocieties: Society[] = [
  {
    id: 'soc-1',
    name: 'Korus',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754213460/Screenshot_2025-08-03_150035_vzrcs2.png',
    aiHint: 'logo',
    description: 'Korus is the official “Music and Dance Society” of KIIT. Korus, has the aim to produce talents from the hub of KSAC. As studies can’t make a student all perfect, Korus helps them to get exposures in the field of Music and Dance. Korus gives the students all the opportunities to make them better. This society provides them Platforms to show their talent and enrich themselves with experience and self confidence. Music and Dance gives a student break from their daily boring life and Korus provides a good way to utilize this passion for their future establishment.',
  },
  {
    id: 'soc-2',
    name: 'Kalakaar',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754213973/Screenshot_2025-08-03_150850_efhz00.png',
    aiHint: 'logo',
    description: 'Kalakaar is the official “Dramatic Society” of KIIT. Kalakaar works with Theater and Nukkad in KIIT. It organizes all the Dramatic competitions that happen on the premises of KIIT. It has some theater and nukkad groups that work hard all year to produce some good content and create awareness in KIIT as well as all over Bhubaneswar. Kalakaar is one of the biggest societies in KIIT and KSAC. It espies the talents in the University and gives the exposures to enrich themselves with experience in the Fields Theater and Nukkad.',
  },
  {
    id: 'soc-3',
    name: 'Kreative Eye',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754214175/Screenshot_2025-08-03_151208_x0u6al.png',
    aiHint: 'logo',
    description: 'Photography is another way to see the environment, while painting gives us the physical experience of imagination. Kreative Eye, the official society of KIIT works on these fields. They capture the beautiful moments in our life in KIIT and make them memorable for our entire life. The decorations we can imagine become real with the expert hands of the members of this society. Kreative Eye digs out the talents and uncovers their hidden powers to deliver beautiful Paintings to reach the hearts of the students of KIIT University',
  },
  {
    id: 'soc-4',
    name: 'Kzarshion',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754214426/Screenshot_2025-08-03_151546_l7cykh.png',
    aiHint: 'logo',
    description: 'We all want to acquire a perfect style statement in our daily life. In our life we all have an image of our perfect role model. But what if we think in a different way? What if we create our own style statement? Kzarshion, the official “Fashion Society” of KIIT helps your dreams come true. It trains the students to become their own role model. They start designing dresses and grooming themselves to become a perfect model whom we dreams of. Kzarshion conducts Ramp Walks and Photo-shoots in various events in KIIT and gives the stylist students a new way to lead rest of their life. The success story of Kzarshion is long and the door is always open for the fashion sensible students in KIIT.',
  },
  {
    id: 'soc-5',
    name: 'Keurig',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754214540/Screenshot_2025-08-03_151832_awizii.png',
    aiHint: 'logo',
    description: 'Who doesn’t love to taste food? Some people say, Cooking is an Art and according to that the food lovers of KIIT are not less than an artist as they try new cooking methods and delicious food preparations to give heavenly feelings to our tongues. Keurig, the official “Cooking Society” of KIIT conducts workshops on Cooking and organizes an event named “Mismatch” in KIIT Fest. Keurig, always welcomes all the food lovers of KIIT to join the revolution and to invent a new era of food with their passion for cooking and love for food.',
  },
  {
    id: 'soc-6',
    name: 'Qutopia',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754214693/Screenshot_2025-08-03_152120_ugwoqs.png',
    aiHint: 'logo',
    description: 'Qutopia is the official “Quizzing Society” of KIIT. It works on regular development of the knowledge of students in each and every fields of the world. Qutopia organizes all the quizzing competitions that happen on the premises of KIIT. The senior Qutopia team has bagged many successes with their vast knowledge and incredible learning. The expert brain passes the knowledge through workshops and training sessions to their juniors. Quizzing makes a student smart and confident, and Qutopia makes sure of it. Through all these year’s knowledge made this society one of the most effective societies of KIIT',
  },
  {
    id: 'soc-7',
    name: 'Kronicle',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754214980/Screenshot_2025-08-03_152501_ck26ln.png',
    aiHint: 'logo',
    description: 'Kronicle is the literary ( Debating ) society of KIIT University. For good ideas and true innovation, you need human interaction, conflict, argument and debate. Here, at Kronicle, we learn not just how to win an argument but convince the masses with logic and reasoning. One can develop a variety of soft skills like fluently speaking with logic, embracing their analytical skills and also to become a good listener, all of which holds a stringent importance in the corporate world. The active members of the society get a range of opportunities to participate in national and international level debate, extempore and symposium. Kronicle also hosts few of the most eminent and prestigious events of our University like Pratijja and Founder’s cup. The knowledge and experience that one gains here is profound and of great significance in their overall personality development.',
  },
  {
    id: 'soc-8',
    name: 'Kalliope',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754215185/Screenshot_2025-08-03_152929_lyyyhv.png',
    aiHint: 'logo',
    description: 'While in ancient greek mythology calliope is the goddess of literature and art, we at KALLIOPE preside over eloquence and the ecstatic harmony of voicesA society dedicated to anyone who loves the stage, lights as bring as the sun, a podium, and words that can embellish any event.We honor your speaking talent and give you the opportunity to act as an anchor at major college fests and events.Anchoring is much more than just fame, it is the voice to an idea, it is countless memories and experiences that shape your life. Mics are our magic wands and we bring smiles on multiple faces just by our words.With a love for public speaking and anchoring, the stage doesn’t frighten us rather it is the place that feels like home',
  },
  {
    id: 'soc-9',
    name: 'KIIT Wordsmith',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754215397/Screenshot_2025-08-03_153306_lljwn8.png',
    aiHint: 'logo',
    description: 'Writing is a way to express feelings. No matter what, a pen is still mightier than a sword and KIIT Wordsmith, the official “Writing Society” helps the writers of KIIT to become experts to express what they feel. In our daily life, we have no substitute of writing. It can be content writing; can be poems, short stories. But if we write in a beautiful way, it gets better and attractive. It may get you what you want. Keeping this in mind, KIIT Wordsmith provides all the knowledge to the students of KIIT and conducts various competitions to give a platform to the writers. It also publishes a magazine with the contents of the lovable KIITians. Writing has no boundaries and so as KIIT Wordsmith. It always welcomes the talented writers on its deck.',
  },
  {
    id: 'soc-10',
    name: 'Khwahishein',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754215697/Screenshot_2025-08-03_153612_l9b20l.png',
    aiHint: 'logo',
    description: 'Communicating with people is important and for that we need to learn the exact way to deliver a speech. We need to learn the language. In Odisha, most of the people know Hindi language and Khwahishein, the official “Hindi Society” makes the students of KIIT capable of reading, writing and expressing in Hindi. The students get training and suggestions from experts to improve their language and starts reaching the common people. Common people are the biggest inspiration to write and if we don’t know the common language it is really hard to get to them. Khahishein provides big platforms to express their writings in Hindi and gives the students immense pleasure to communicate in their own soulful language.',
  },
  {
    id: 'soc-11',
    name: 'Khwaab',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754215793/Screenshot_2025-08-03_153942_bax8dg.png',
    aiHint: 'logo',
    description: 'Khwaab is the official “Social Service Society” of KIIT. The philosophies of “Art of Giving”, “Kompassion” and “India against Negativity” of our Honorable Founder Dr. Achyutya Samanta Sir are the main inspiration of this society. It works on the rural areas of Bhubaneswar to make this city clean, aware and better one. The students of KIIT and members of Khwaab work hard every day to make him proud with their social works and welfare activities all over the city. Khwaab welcomes all the socially active students of KIIT to join their selfless giving activities for good cause and a bright future.',
  },
  {
    id: 'soc-12',
    name: 'KIIT Film Society',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754216166/Screenshot_2025-08-03_154515_ie5va3.png',
    aiHint: 'logo',
    description: 'Films have a great impact in our life. On screen imaginations drive us through our entire life. KFS (KIIT Film Society), the official “Film making Society” of KIIT helps the students of KIIT to get the real feeling of “Lights, Camera and Action”. When light falls on you and the camera rolls, the entire universe changes. KFS has the unique ability to give the students of KIIT a platform where they can be their own Heroes. No more dreaming of being in a film, students can be in it with their talents and capabilities. KFS provides workshops to improve acting skills, cinematography skills, and Direction skills. KFS conducts KIFF (Kalinga International Film Festival) where they welcome all the enthusiastic students, where they can submit their films and get a chance to get screened. KFS helps to make true what a student dreams of. This is where our passion becomes our life.',
  },
  {
    id: 'soc-13',
    name: 'Kamakshi & HeForShe',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754216399/Screenshot_2025-08-03_154947_lap4qr.png',
    aiHint: 'logo',
    description: ' Kamakshi and HeForShe are the two societies formed for the women of the University. At present we all can see what girls are facing all over the India and these societies aim to cure this inhuman disease with awareness and good cause. These societies got merged and they became the official society of KIIT to protect and aware girls and boys about the situations humans are facing in daily life. Learning self protection is not enough now, if “He” doesn’t stand For “She” then all the efforts to protect women in our country will be in vain. With this great aim and cause these societies works each and every day to educate the students and all the people of Bhubaneswar. We need to stand and we need to protect our girls, so at this very situation of this country, Kamakshi & HeForShe is one of the most sensitive and important societies in KIIT.',
  },
  {
    id: 'soc-14',
    name: 'TEDX-KU',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754216565/Screenshot_2025-08-03_155234_tgpmk9.png',
    aiHint: 'logo',
    description: 'TEDX-KU, the official society of KIIT is aimed to provide a first-hand TED experience to its attendees. It offers a platform to integrate new people into the TED community which helps them to bridge the gap between ideas and actions.Communication is an indispensable part of our daily lives. The more we communicate, the more our minds intertwine with one another and eventually assist us in formulating certain notions. The TEDx community bestows us with the opportunity to navigate through ideas having a probability of bringing about unparalleled transitions which will ultimately work for the amelioration of the society. Venturing into uncharted territories has always been a challenging encounter. The maiden edition of TEDxKIITUniversity was a unique and unprecedented achievement in itself. The exceptional levels of success attained in the next two editions that ensued, speak volumes about the possible ideas that are capable of helping us conceive monumental metamorphosis to the society.',
  },
  {
    id: 'soc-15',
    name: 'MUN-SOC',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754216763/Screenshot_2025-08-03_155516_qpudu6.png',
    aiHint: 'logo',
    description: 'Model United Nations, also known as Model UN or MUN, is an extra-curricular activity in which students typically role-play delegates to the United Nations and simulate UN committees. In KIIT, the official society, MUN-SOC conducts one of the biggest events of Bhubaneswar as well as India. It is a three days event where the interested students show their delegation capabilities and competes with the outside students from all over the India. MUN-SOC provides the young Delegates a good platform to unleash their knowledge and fluency on a country. It helps the students to gain confidence and helps them to walk a mile ahead to their bright future.',
  },
  {
    id: 'soc-16',
    name: 'Intl. Student Society',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754216881/Screenshot_2025-08-03_155747_ppp7oh.png',
    aiHint: 'logo',
    description: 'KIIT International Student Society is an official society of KIIT Deemed to be University functioning at KIIT Student Activity Centre for all the international students who are in the University for their studies.  This society helps in building up relationships and networking with students of different countries and promotes an ecosystem of inclusiveness, international friendship while celebrating their cultural diversity. The international students take part in various activities through this society and they get connected with each and everyone in the University',
  },
  {
    id: 'soc-17',
    name: 'Kimaya',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754217322/Screenshot_2025-08-03_160401_o8neas.png',
    aiHint: 'logo',
    description: 'Kimaya, the official “Medical Society” of KIIT aims to create health awareness among common people, Managing and helping in natural calamities, building up doctor-patient relationships and language skill development of the students. It also cconducts seminars, CMEs, quizzes, debates, workshops, Nukkad-Natak, flash mobs on health related matters. Helping orphanages, the underprivileged and old age homes and teaching and learning minor ambulatory procedures are the high priorities of this society. No doubt, this is one of the most important societies in KIIT.',
  },
  {
    id: 'soc-18',
    name: 'Kraya & Kuber',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754217507/Screenshot_2025-08-03_160813_b7tiun.png',
    aiHint: 'logo',
    description: 'Marketing is the soul of any industry and institution. It helps them to reach to each and every corner of this large country and Kraya, the official “Marketing & Finance Society” of KIIT helps this institute to have good promotion on each and every aspect. “Marketing” is a race without a finishing line, it is no longer about the stuffs we make, but about the stories we tell. So, Kraya & Kuber works on exploring the talents in the marketing field in this University and helps the students to bring out the Marketer hidden inside of them.',
  },
  {
    id: 'soc-19',
    name: 'Welfare Society',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754217799/Screenshot_2025-08-03_161122_c0egb9.png',
    aiHint: 'logo',
    description: 'The official KIIT Animal & Environment Welfare Society works hard to keep our environment safe for us as well as for the animals. The main motto of this Society is “Pause for a Cause”. The Society is a group of enthusiastic and experienced people who have great affection towards our Animal friends and Environment. Throughout the year they organize various events related to Animal Rights & Welfare and Environmental Causes. Apart from events, KIIT-AEWS’s Volunteer Wing looks after injured and needy animals in and around Bhubaneswar City in Odisha, India.',
  },
  {
    id: 'soc-20',
    name: 'Kraftovity',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754218093/Screenshot_2025-08-03_161803_gzzqir.png',
    aiHint: 'logo',
    description: 'The official “Crafting Society” of KIIT has a beautiful name, Kraftovity. The decorations we see all around us, the design and structures we crave for comes from the expert minds of this society. It has got enormous success in the field of Crafting and decorations. An artist must have the knowledge to reach the people’s heart and crafting gives us the physical 3D experiences of our most beautiful imaginations. Keeping these two things in mind, Kraftovity always makes the people love their work. They work with love, passion and strong will to reach the entire world. This official society conducts many sessions and workshops to provide the students of KIIT a good knowledge of crafting. The event that happens on the field of KIIT becomes beautiful with the help of this beautiful society.',
  },
  {
    id: 'soc-21',
    name: 'SPIC MACAY',
    category: 'Cultural',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754218183/Screenshot_2025-08-03_161929_zl7lcv.png',
    aiHint: 'logo',
    description: 'The official society of KIIT for the “Promotion of Indian Classical Music And Culture Aamongst Youth” (SPIC MACAY) is a voluntary youth movement which promotes intangible aspects of Indian cultural heritage by promoting Indian classical music, classical dance, folk music, yoga, meditation, crafts and other aspects of Indian culture. KIIT SPIC MACAY welcomes all the classical minded and enthusiastic students to be a part of this revolution to keep the tradition alive.',
  },
  {
    id: 'soc-22',
    name: 'Enactus',
    category: 'Social',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754218563/Screenshot_2025-08-03_162550_ycikck.png',
    aiHint: 'logo',
    description: 'ENACTUS KISS-KIIT is an innovative initiative by some students of KIIT to improve the quality of life in society. Under the initiative, in 2016, Project SIDDHI was undertaken, which provided opportunity to the oppressed communities in and around Bhubaneswar to change their lives for the better and, in the process, eliminate the use of plastic bags by replacing it with handmade paper bags. Not only that they have done some incredible works to improve the quality of life. Enactus is always thankful to Dr. Achutya Samanta, Founder, and KIIT & KISS for encouraging them for different ventures.',
  },
  {
    id: 'soc-23',
    name: 'Konnexions',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754218712/Screenshot_2025-08-03_162818_rr9yh4.png',
    aiHint: 'logo',
    description: 'IT and Web Development has a bright future, so here in KIIT Konnexions, the official society focuses on improving the skills of the students to provide them the most beautiful career and life. It has a mission to provide and foster professional advancement opportunities among individuals (students) dedicated to a App Development and Web career, and to work diligently to enhance their effectiveness, image, and professionalism as they can outperform others in this field and bring glory to the university.',
  },
  {
    id: 'soc-24',
    name: 'Robotics Society',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754218882/Screenshot_2025-08-03_163050_xucwso.png',
    aiHint: 'logo',
    description: 'KRS (KIIT ROBOTICS SOCIETY) focuses on research, knowledge sharing and learning with the aim of embracing new technology and making new discoveries in the field of Robotics with a high standard of ethics in service to the community. It enriches the enthusiastic students with technical knowledge and helps them with all types of supports to uncover their imaginations. Innovations come with great imaginations. So, KRS always ask students to dream for a perfect technology to make our life easier.',
  },
  {
    id: 'soc-25',
    name: 'Civil Engineer Society',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754219165/Screenshot_2025-08-03_163528_g6brmu.png',
    aiHint: 'logo',
    description: 'KIIT Society for Civil Engineers helps the students of the CIVIL Department to embrace the seniors and more experienced people of the Department. It provides many opportunities to interact with the stream out of your books. It helps students to get exposed to the real world of engineering to be a Smart Engineer. Civil Engineers are the Pillars of a society and this whole team works hard to make the students capable to handle the responsibilities.',
  },
  {
    id: 'soc-26',
    name: 'Apogeio',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754220520/Screenshot_2025-08-03_165737_t4walo.png',
    aiHint: 'logo',
    description: 'Apogeio the official “Aeronautical Society” of KIIT is working on space and the technologies to reach there. Children like us always dreams of the space, the mystery of it. Here Apogeio helps these dreamy students to reach their dreams. Apogeio focuses on research, knowledge sharing and learning with the aim of embracing new technology and making new discoveries in the field of Aeronautics with a high standard of ethics in service to the community. It welcomes all the enthusiastic students and high knowledge.',
  },
  {
    id: 'soc-27',
    name: 'Automobile Society',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754220827/Screenshot_2025-08-03_170332_kknv3x.png',
    aiHint: 'logo',
    description: 'KIIT Automobile Society always focuses on the new discoveries and easier way to live a life. It has an immense interest of making cars and mobile devices ECO friendly. This official society of KIIT has produced some fantastic designs and mechanism which is already helping a large amount of people. The evergreen and ever growing mechanical industry witnesses an ongoing enormous development in its technology and application methodologies. It has proved its stability even during the economic recession and has also captured the attention of the whole world with some innovative products. Carrying with the innovation, automobile society aims to instill that in student, and helps them to create technical resources which can help the human society.',
  },
  {
    id: 'soc-28',
    name: 'AISOC',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754419524/IMG_20250806_000004_xjuu1v.jpg',
    aiHint: 'logo',
    description: 'AISoC is your global haven for passionate AI minds — where technology meets ethics to shape a better future. Connect with industry leaders, researchers, and peers worldwide. Learn through tailored education, hands-on projects, and impactful research. Champion ethical AI, contribute to open-source, and take part in student-led innovation. Beyond the classroom, AISoC offers career guidance, global insights, and AI-powered media to keep you informed and empowered. Join us to explore, create, and lead in the world of AI — one innovative step at a time.',
  },
  {
    id: 'soc-29',
    name: 'GFG KIIT',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754458186/IMG_20250806_000123_uvfgey.jpg',
    aiHint: 'logo',
    description: 'GFG KIIT is the official GeeksforGeeks Student Chapter at Kalinga Institute of Industrial Technology (KIIT), dedicated to nurturing a strong community of tech enthusiasts, problem solvers, and future innovators.Driven by the spirit of learn, code, and grow, we empower students with practical skills in Data Structures & Algorithms, Competitive Programming, Web & App Development, Open Source, and more.Through workshops, coding contests, speaker sessions, and peer mentorship, we bridge the gap between classroom learning and real-world tech demands.',
  },
  {
    id: 'soc-30',
    name: 'IOT KIIT',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754458186/IMG_20250805_235937_riietw.jpg',
    aiHint: 'logo',
    description: 'IoT KIIT is a vibrant community of dedicated students and faculty at KIIT, united by a shared mission: leveraging technology for the betterment of society. We believe that even the smallest innovations can spark meaningful change — and we work every day to turn that belief into reality.While rooted as a research lab, our strength lies in our holistic, in-house ecosystem. From hardware and software development to design, communication, and operations — we embrace both technical and non-technical domains to deliver well-rounded, impactful solutions.',
  },
  {
    id: 'soc-31',
    name: 'GDSC Society',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754458186/IMG_20250806_000036_xvwft9.jpg',
    aiHint: 'logo',
    description: 'Google Developer Student Clubs KIIT is a technical club focused on building a community of student developers interested in solving real-world problems.We host various workshops and hackathons. We also host flagship events from Google such as Android Study Jams, 30 days of Google Cloud, ExploreML etc.Our goal is to build an inclusive community of students who want to learn about tech and grow together.',
  },
  {
    id: 'soc-32',
    name: 'MLSA KIIT',
    category: 'Technical',
    logo: 'https://res.cloudinary.com/dvossdvzk/image/upload/v1754458186/IMG_20250806_000058_cxdyvh.jpg',
    aiHint: 'logo',
    description: 'MLSA KIIT is the official chapter of the Microsoft Learn Student Ambassadors program at Kalinga Institute of Industrial Technology (KIIT). We are a community of passionate students driven by a common goal — to empower peers through technology, collaboration, and innovation. We believe in the power of knowledge sharing and hands-on learning to create a positive impact on our campus and beyond.',
  },

];

// export function getSocietyById(id: string): Society | undefined {
//     return allSocieties.find(society => society.id === id);
// }

export async function getSocietyById(id: string): Promise<Society | undefined> {
  return allSocieties.find((s) => s.id === id);
}